// Course API
export const CHANGE_TRENDING_COURSES_PAGE = "CHANGE TRENDING COURSES PAGE";
export const GET_COURSE_DETAIL= "GET COURSE DETAIL";
export const GET_COURSES="GET COURSES";
export const POST_TRENDING_COURSES = "POST_TRENDING_COURSES";
export const POST_COURSES_IN_CATEGORY = "POST_COURSES_IN_CATEGORY";

// User API
export const GET_USER_LIST= "GET USER LIST";
export const POST_USERINFO = "POST_USERINFO";
