// Course API
export const CHANGE_TRENDING_COURSES_PAGE = "CHANGE TRENDING COURSES PAGE";
export const GET_COURSES="GET COURSES";
export const POST_TRENDING_COURSES = "POST TRENDING COURSES";
export const POST_COURSES_IN_CATEGORY = "POST COURSES IN CATEGORY";
export const POST_COURSE_DETAIL = "POST COURSE DETAIL";
export const POST_PENDING_COURSES = "POST PENDING COURSES";
export const POST_REGISTERED_COURSES = "POST REGISTERED COURSES";
export const UPDATE_PENDING_COURSES = "UPDATE PENDING COURSES";
export const REMOVE_PENDING_COURSE = "REMOVE PENDING COURSE";
export const POST_ALL_COURSES = "POST ALL COURSES";

// User API
export const GET_USER_LIST= "GET USER LIST";
export const POST_USERINFO = "POST USERINFO";
export const UPDATE_USERINFO = "UPDATE USERINFO";
export const DELETE_USERINFO = "DELETE USERINFO";
export const SEARCH_USER= "SEARCH USER";



//Management API
export const REMOVE_USER_MANAGEMENT= "REMOVE USER MANAGEMENT";
