// Course API
export const CHANGE_TRENDING_COURSES_PAGE = "CHANGE TRENDING COURSES PAGE";
export const GET_COURSE_DETAIL= "GET COURSE DETAIL";
export const GET_COURSES="GET COURSES";


// User API
export const GET_USER_LIST= "GET USER LIST";